### ISSUE TITLE
Player icon does not update

### ISSUE THREAD

**Issue by ionyx0** [kkamperschroer/Musicality#144]
The icon in the Chrome task bar does not update.  I have tested this with Amazon Music and Pandora.  Chrome Version: 48.0.2564.97 m

**Comment by kkamperschroer** [comment]
Thanks for the report! Pretty busy with other projects, but if I find some time to work on this I will.

**Comment by ionyx0** [comment]
If this helps...  I'm not familiar enough with the code to fix myself.

```
Error in response to tabs.get: TypeError: Cannot read property 'IsStillPlayingMusic' of undefined
    at chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/background/musicality.js:2:1335
    at Object.callback (chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/background/helper.js:2:495)
    at Object.Helper.DoesTabExist (chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/background/helper.js:2:463)
    at Musicality.updateInformation (chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/background/musicality.js:2:1288)
    at Musicality.GetPlaybackInfo (chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/background/musicality.js:2:2698)
    at UpdateInformation (chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/popup/popup.js:2:101)
    at chrome-extension://fjiolbglibkahkipcdgeepdfdgfkdbee/js/popup/popup.js:2:5538
```

**Comment by imjennyli** [comment]
:+1:  I've seen that stack trace too.. but sometimes it works for me.

**Comment by thetrekker** [comment]
With these changes all buttons function properly when present.  Amazon has either ThumbsUp/ThumbsDown buttons OR Shuffle/Repeat buttons BUT NEVER ALL FOUR.
The artwork displays properly.
TimeElapsed/TotalTime displays properly.


`{
    "name" : "Amazon",

"COMMENT_1" : "This block contains all of the things a player may or may not have",

    "has_thumbs_up" : "$('.thumbsUpButton').length > 0||$('.thumbsDownButton').length > 0",
    "has_thumbs_down" : "$('.thumbsUpButton').length > 0||$('.thumbsDownButton').length > 0",
    "has_next_track" : true,
    "has_prev_track" : true,
    "has_play_pause" : true,
    "has_shuffle" : "$('.shuffleButton').length > 0||$('.repeatButton').length > 0",
    "has_repeat" : "$('.shuffleButton').length > 0||$('.repeatButton').length > 0",
    "has_current_track_time" : true,
    "has_total_track_time" : false,
    "has_remaining_track_time" : true,

"COMMENT_2" : "This block contains all boolean values we can get back from the player",

    "isPlaying" : "$('.button.playerIcon.playButton').hasClass('playerIconPause')",
    "isPaused" : "!$('.button.playerIcon.playButton').hasClass('disabled') && $('.button.playerIcon.playButton').hasClass('playerIconPlay')",
    "isShuffled" : "$('.shuffleButton').hasClass('on')",
    "isRepeatOff" : "!$('.repeatButton').hasClass('on')",
    "isRepeatAll" : "$('.repeatButton').hasClass('on')",
		"isThumbedUp" : "$('.thumbsUpButton').hasClass('on')",
    "isThumbedDown" : "$('.thumbsDownButton').hasClass('on')",

"COMMENT_3" : "This block contains all string values we can get back from the player",

    "artUrl" : "$('.largeAlbumArtContainer .art').attr('style').split('background-image: url(\"')[1].split('\")')[0]",
    "artist" : "$('.trackArtist a span').text()",
    "track" : "$('.trackTitle a span').text()",
    "currentTime" : "$('.songDuration.timeElapsed').text()",
    "remainingTime" : "$('.songDuration.timeRemaining').text()",

"COMMENT_4" : "Finally, this block contains info on how to perform actions",

    "click_play" : "$('.playbackControlsContainer .playbackControls .button.playButton').trigger('click')",
    "click_pause" : "$('.playbackControlsContainer .playbackControls .button.playButton').trigger('click')",
    "click_next_track" : "$('.playbackControlsContainer .playbackControls .button.nextButton').trigger('click')",
    "click_prev_track" : "$('.playbackControlsContainer .playbackControls .button.previousButton').trigger('click')",
    "click_shuffle" : "$('.playbackControlsContainer .playbackControls .button.shuffleButton').trigger('click')",
    "click_repeat" : "$('.playbackControlsContainer .playbackControls .button.repeatButton').trigger('click')",
		"click_thumbs_up" : "$('.playbackControlsContainer .playbackControls .button.thumbsUpButton').trigger('click')",
    "click_thumbs_down" : "$('.playbackControlsContainer .playbackControls .button.thumbsDownButton').trigger('click')"
}
`

**Comment by kkamperschroer** [comment]
Thanks @thetrekker! As soon as I can I'll pull in your changes and try it out myself. If it works I'll push out a new release.

**Comment by thetrekker** [comment]
FYI, the Chromium & Chrome are both on Ubuntu 16.04 (64-bit).... I also run
on Windows 8.1 & Windows 10 machines.  I'll try to test these machines
today and get back with you.

**Comment by thetrekker** [comment]
Also AWESOME response time... :)
